# Assignment 9: NumPy (Mathematical & Statistical Operations)

## Task 1: Creating NumPy Arrays

In [ ]:
'''
1. Import NumPy as np.
2. Create the following arrays:
o A 1D array of integers from 1 to 10
o A 2D array of shape (3, 3) with values from 1 to 9
o A NumPy array from the list: [10, 20, 30, 40, 50]
3. Print:
o Shape of each array
o Data type of each array
'''
# import numpy library
import numpy as np

# 1D array
arr1 = np.array(range(1,11))
# another way
arr1 = np.arange(1,11)
print(arr1)
print("Type of array 1: ", type(arr1))
print("Shape of array 1: ", arr1.shape)

# 2D array
arr2 = np.array(range(1, 10))
arr2 = arr2.reshape((3,3))
print(arr2)
print("Type of array 2: ", type(arr2))
print("Shape of array 2: ", arr2.shape)

# another way of creating 2D array
arr2 = np.array([[1,2,3], [4,5,6],[7,8,9]])
print(arr2)
print("Type of array 2: ", type(arr2))
print("Shape of array 2: ", arr2.shape)

# creating array using list of numbers
arr3 = np.array([10, 20, 30, 40, 50])
print(arr3)
print("Type of array 3: ", type(arr3))
print("Shape of array 3: ", arr3.shape)


[ 1  2  3  4  5  6  7  8  9 10]
Type of array 1:  <class 'numpy.ndarray'>
Shape of array 1:  (10,)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Type of array 2:  <class 'numpy.ndarray'>
Shape of array 2:  (3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Type of array 2:  <class 'numpy.ndarray'>
Shape of array 2:  (3, 3)
[10 20 30 40 50]
Type of array 3:  <class 'numpy.ndarray'>
Shape of array 3:  (5,)


## Task 2: Important Mathematical Operations

In [16]:
'''
Given two arrays:
A = np.array([10, 20, 30, 40])
B = np.array([1, 2, 3, 4])
Perform and print results for:
1. Addition (A + B)
2. Subtraction (A - B)
3. Multiplication (A * B)
4. Division (A / B)
5. Power (A ** 2)
Extra (optional): Use NumPy functions: np.add(), np.subtract() for the same operations.
'''

import numpy as np
A = np.array([10, 20, 30, 40])
B = np.array([1, 2, 3, 4])
# Addition
op = np.add(A, B)
print("Addition of 2 arrays: ", op)

# Subtraction
op = np.subtract(A, B)
print("subtract of 2 arrays: ", op)

# Multiplication
op = np.multiply(A, B)
print("Multiplication of 2 arrays: ", op)

# Division
op = np.divide(A, B)
print("Division of 2 arrays: ", op)

# Power
op = np.power(A, 2)
print("squaring of array A: ", op)

# Another way of doing above operations
# Addition
op = A+B
print("Addition of 2 arrays: ", op)

# Subtraction
op = A-B
print("subtract of 2 arrays: ", op)

# Multiplication
op = A*B
print("Multiplication of 2 arrays: ", op)

# Division
op = A//B # floor division
print("Division of 2 arrays: ", op)

# Power
op = A**2
print("squaring of array A: ", op)


Addition of 2 arrays:  [11 22 33 44]
subtract of 2 arrays:  [ 9 18 27 36]
Multiplication of 2 arrays:  [ 10  40  90 160]
Division of 2 arrays:  [10. 10. 10. 10.]
squaring of array A:  [ 100  400  900 1600]
Addition of 2 arrays:  [11 22 33 44]
subtract of 2 arrays:  [ 9 18 27 36]
Multiplication of 2 arrays:  [ 10  40  90 160]
Division of 2 arrays:  [10 10 10 10]
squaring of array A:  [ 100  400  900 1600]


## Task 3: Important NumPy Mathematical Formulas

In [24]:
''' 
Given:
values = np.array([2, 4, 6, 8, 10])
Calculate:
1. Square root of each element
2. Exponential of each element
3. Natural logarithm of each element
4. Sum of all elements
5. Cumulative sum of elements
Use NumPy functions only.
'''
values = np.array([2, 4, 6, 8, 10])

print("Original Array: \n", values)

# Square root
op = values**(1/2)
# another way
op = np.sqrt(values)
print("square root of array values: \n", op)

# Exponential
op = np.exp(values)
print("Exponential of array values: \n", op)

# natural log
op = np.log(values)
print("Natural log of array values: \n", op)

# Sum of all elements
op = np.sum(values)
print("Sum of all elements: \n", op)

# Cumulative sum of elements
op = np.cumsum(values)
print("Cumulative Sum of all elements: \n", op)


Original Array: 
 [ 2  4  6  8 10]
square root of array values: 
 [1.41421356 2.         2.44948974 2.82842712 3.16227766]
Exponential of array values: 
 [7.38905610e+00 5.45981500e+01 4.03428793e+02 2.98095799e+03
 2.20264658e+04]
Natural log of array values: 
 [0.69314718 1.38629436 1.79175947 2.07944154 2.30258509]
Sum of all elements: 
 30
Cumulative Sum of all elements: 
 [ 2  6 12 20 30]


## Task 4: Aggregation Operations

In [30]:
''' 
Given a 2D array:
data = np.array([
[10, 20, 30],
[40, 50, 60],
[70, 80, 90]
])
Find:
1. Row-wise sum
2. Column-wise sum
3. Minimum value
4. Maximum value
5. Overall mean
'''
data = np.array([
[10, 20, 30],
[40, 50, 60],
[70, 80, 90]
])

# Rowise Sum of elements
op = np.sum(data, axis=1)
print("Rowise Sum of elements: \n", op)

# Columnwise Sum of elements
op = np.sum(data, axis=0)
print("Columnwise Sum of elements: \n", op)

# Minimum Value
op = np.min(data)
print("Minimum Value: \n", op)

# Maximum Value
op = np.max(data)
print("Maximum Value: \n", op)

# Overall Mean
op = np.mean(data)
print("Overall Mean: \n", op)

Rowise Sum of elements: 
 [ 60 150 240]
Columnwise Sum of elements: 
 [120 150 180]
Minimum Value: 
 10
Maximum Value: 
 90
Overall Mean: 
 50.0


## Task 5: Statistical Operations (Core Focus)

In [ ]:
''' 
marks = np.array([78, 85, 90, 66, 72, 88, 95, 60])
Calculate and print:
1. Mean
2. Median
3. Variance
4. Standard Deviation
5. Minimum & Maximum
6. Range (max - min)
'''
marks = np.array([78, 85, 90, 66, 72, 88, 95, 60])

# Mean
op = np.mean(marks)
op = marks.mean() # another way
print("Mean Marks: \n", op)

# Median
op = np.median(marks)
print("Median Marks: \n", op)

# Variance
op = np.var(marks)
print("Variance Marks: \n", op)

# Standard Deviation
op = np.std(marks)
print("Standard Deviation Marks: \n", op)

# Maximum
op = np.max(marks)
print("Maximum Marks: \n", op)

# Minimum
op = np.min(marks)
print("Minimum Marks: \n", op)

# Range (max-min) # 95-60 = 35
op = np.ptp(marks)
print("Range (max-min) Marks: \n", op)


Mean Marks: 
 79.25
Median Marks: 
 81.5
Variance Marks: 
 134.1875
Standard Deviation Marks: 
 11.583932838203095
Maximum Marks: 
 95
Minimum Marks: 
 60
Range max to min Marks: 
 35


## Task 6: Percentiles & Sorting

In [46]:
''' 
Using the same marks array:
1. Sort the array
2. Find:
o 25th percentile
o 50th percentile
o 75th percentile
3. Count how many students scored above the average marks
'''

# Sorting of the marks
op = np.sort(marks)
print("Sorted Marks: ", op)

# percentile
op = np.percentile(marks, [25, 50, 75])
print('Percentile', op)

# Another way of percentile
# percentile 25
op = np.percentile(marks, 25)
print('Percentile 25: ', op)

# percentile 50
op = np.percentile(marks, 50)
print('Percentile 50: ', op)

# percentile 75
op = np.percentile(marks, 75)
print('Percentile 75: ', op)

# Count of students score above the avg marks
mean_marks = np.mean(marks)
op= np.sum(marks>mean_marks)
print('Comparison: ', marks>mean_marks)
print('Count of students score above the avg marks: ', op)

Sorted Marks:  [60 66 72 78 85 88 90 95]
Percentile [70.5 81.5 88.5]
Percentile 25:  70.5
Percentile 50:  81.5
Percentile 75:  88.5
Comparison:  [False  True  True False False  True  True False]
Count of students score above the avg marks:  4


## Task 7: Mini Use Case: Sales Analysis

In [48]:
''' 
Given daily sales data:
sales = np.array([1200, 1500, 900, 2000, 1800, 1700, 1600])
Perform:
1. Total weekly sales
2. Average daily sales
3. Highest and lowest sales day
4. Standard deviation of sales
5. Identify days where sales were above average
'''
sales = np.array([1200, 1500, 900, 2000, 1800, 1700, 1600])

# 1. Total weekly sales
print("Total weekly Sales: ", np.sum(sales))

# 2. Average daily sales
print("Average daily Sales: ", np.mean(sales))

# 3. Highest and lowest sales day
print("Highest Sale : ", np.max(sales))
print("Lowest Sale : ", np.min(sales))

# 4. Standard deviation of sales
print("Standard Deviation of Sales : ", np.std(sales))

# 5. Identify days where sales were above average
mean_sale = np.mean(sales)
print("Days where sales were above average : ", np.sum(sales>mean_sale))



Total weekly Sales:  10700
Average daily Sales:  1528.5714285714287
Highest Sale :  2000
Lowest Sale :  900
Standard Deviation of Sales :  345.2298849598449
Days where sales were above average :  4
